#!/bin/bash

declare -i tries=5

while [[ $tries>0 ]]; do
  ssh -q -o ConnectTimeout=10 -o StrictHostKeyChecking=no $*
  rc=$?
  if [[ $rc != 255 ]]; then exit $rc ; fi
  echo "$tries tries remaining"
  tries+=-1
done
